version: '3'

networks:
  default:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  graphql:
    build:
      context: ./graphql
      dockerfile: ./Dockerfile
    links:
      - rabbitmq
    ports:
      - 4000:4000
  brewgorithm:
    build:
      context: ./brewgorithm
      dockerfile: ./Dockerfile
    links:
      - rabbitmq
    ports:
      - 5000:5000

