version: '3'

networks:
  default:

services:

  api:
    build: .
    environment:
      RATEBEER_DB_USERNAME: ratebeer_db_username
      RATEBEER_DB_PASSWORD: ratebeer_db_password
      AWS_ID_SECRET: brewgorithm_aws_id
      AWS_KEY_SECRET: brewgorithm_aws_key
      WRITE_API: 0
    ports:
      - 5000:5000
    volumes:
      - ../../secrets/brewgorithm_api/ratebeer_db_username:/run/secrets/ratebeer_db_username
      - ../../secrets/brewgorithm_api/ratebeer_db_password:/run/secrets/ratebeer_db_password
      - ../../secrets/brewgorithm_api/brewgorithm_aws_id:/run/secrets/brewgorithm_aws_id
      - ../../secrets/brewgorithm_api/brewgorithm_aws_key:/run/secrets/brewgorithm_aws_key

  write_api:
    build: .
    environment:
      RATEBEER_DB_USERNAME: ratebeer_db_username
      RATEBEER_DB_PASSWORD: ratebeer_db_password
      AWS_ID_SECRET: brewgorithm_aws_id
      AWS_KEY_SECRET: brewgorithm_aws_key
      WRITE_API: 1
    ports:
      - 5001:5000
    volumes:
      - ../../secrets/brewgorithm_api/ratebeer_db_username:/run/secrets/ratebeer_db_username
      - ../../secrets/brewgorithm_api/ratebeer_db_password:/run/secrets/ratebeer_db_password
      - ../../secrets/brewgorithm_api/brewgorithm_aws_id:/run/secrets/brewgorithm_aws_id
      - ../../secrets/brewgorithm_api/brewgorithm_aws_key:/run/secrets/brewgorithm_aws_key
