version: '3'

networks:
  default:

services:

  localstack:
    image: localstack/localstack:0.8.0
    ports:
      - "4576:4576"
      - "4569:4569"
      - "4583:4583"
      - "4572:4572"
      - "8080:8080" # Web UI
    environment:
      - SERVICES=ssm:4583,s3:4572
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


  api:
    build: .
    env_file: .env
    ports:
      - 5000:5000
      - 8000:8000

  write_api:
    build: .
    env_file: .env
    ports:
      - 5001:5000
