version: '3'

networks:
  api:
    external: true

services:

  api:
    image: brewgorithm/brewgorithm-api:${TAG:-latest}
    networks:
      - api
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=5000
        - com.df.servicePath=/model
        - com.df.reqPathSearch=/model
        - com.df.serviceDomain=${SERVICE_DOMAIN}
        - com.df.httpsOnly=true
      mode: replicated
      placement:
        constraints: 
          - node.role == worker
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 1G
