version: '3.3'

networks:
  api:
    external: true

services:

  api:
    image: brewgorithm/brewgorithm-api:${TAG:-latest}
    networks:
      - api
    deploy:
      mode: replicated
      placement:
        constraints: 
          - node.role == worker
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 1G
    secrets:
      - db_username
      - db_password
      - aws_access_key_id
      - aws_secret_access_key

secrets:
  db_username:
    external: true
  db_password:
    external: true
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true