version: '3.3'

networks:
  api:
    external: true

  proxy:
    external: true

services:

  api:
    image: brewgorithm/brewgorithm-api:${TAG:-latest}
    environment:
      RATEBEER_DB_USERNAME: ratebeer_db_username
      RATEBEER_DB_PASSWORD: ratebeer_db_password
      AWS_ID_SECRET: brewgorithm_aws_id
      AWS_KEY_SECRET: brewgorithm_aws_key
      WRITE_API: 0
    networks:
      - api
      - proxy
    deploy:
      replicas: 5
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=5000
        - com.df.servicePath=/model
        - com.df.reqPathSearch=/model
        - com.df.serviceDomain=${SERVICE_DOMAIN}
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 1G
    secrets:
      - ratebeer_db_username
      - ratebeer_db_password
      - brewgorithm_aws_id
      - brewgorithm_aws_key


  write-api:
    image: brewgorithm/brewgorithm-api:${TAG:-latest}
    environment:
      RATEBEER_DB_USERNAME: ratebeer_db_username
      RATEBEER_DB_PASSWORD: ratebeer_db_password
      AWS_ID_SECRET: brewgorithm_aws_id
      AWS_KEY_SECRET: brewgorithm_aws_key
      WRITE_API: 1
    networks:
      - api
      - proxy
    deploy:
      mode: replicated
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=5000
        - com.df.servicePath=/write-model
        - com.df.reqPathSearch=/write-model
        - com.df.serviceDomain=${SERVICE_DOMAIN}
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      placement:
        constraints:
          - node.role == worker
          - node.labels.for == brewgorithm-ai-worker
      resources:
        reservations:
          memory: 6G
        limits:
          memory: 6G
    secrets:
      - ratebeer_db_username
      - ratebeer_db_password
      - brewgorithm_aws_id
      - brewgorithm_aws_key

secrets:
  ratebeer_db_username:
    external: true
  ratebeer_db_password:
    external: true
  brewgorithm_aws_id:
    external: true
  brewgorithm_aws_key:
    external: true
