version: '3.3'

networks:
  api:
    external: true

services:

  api:
    image: brewgorithm/brewgorithm-api:${TAG:-latest}
    environment:
      RATEBEER_DB_USERNAME: ratebeer_db_username
      RATEBEER_DB_PASSWORD: ratebeer_db_password
      RATEBEER_AWS_ID: ratebeer_aws_id
      RATEBEER_AWS_KEY: ratebeer_aws_key
      WRITE_API: 0
    networks:
      - api
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      placement:
        constraints: 
          - node.role == worker
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 1G
    secrets:
      - ratebeer_db_username
      - ratebeer_db_password
      - ratebeer_aws_id
      - ratebeer_aws_key


  write_api:
    image: brewgorithm/brewgorithm-api:${TAG:-latest}
    environment:
      RATEBEER_DB_USERNAME: ratebeer_db_username
      RATEBEER_DB_PASSWORD: ratebeer_db_password
      RATEBEER_AWS_ID: ratebeer_aws_id
      RATEBEER_AWS_KEY: ratebeer_aws_key
      WRITE_API: 1
    networks:
      - api
    ports:
      - 5001:5000
    deploy:
      mode: replicated
      placement:
        constraints: 
          - node.role == worker
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 1G
    secrets:
      - ratebeer_db_username
      - ratebeer_db_password
      - ratebeer_aws_id
      - ratebeer_aws_key

secrets:
  ratebeer_db_username:
    external: true
  ratebeer_db_password:
    external: true
  ratebeer_aws_id:
    external: true
  ratebeer_aws_key:
    external: true